modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL"
issueTrackerURL="https://github.com/hogelog/minecraft-myfirstmod/issues1"
[[mods]]
modId = "myfirstmod"
version = "${file.jarVersion}"
displayName = "My first mod"
displayURL="https://github.com/hogelog/minecraft-myfirstmod"
logoFile = "logo.png"
credits = "hogelog"
authors = "hogelog"
description = '''
This is my first minecraft mod.
'''
[[dependencies.myfirstmod]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.myfirstmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
